// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actions.sql

package sqlcgen

import (
	"context"
)

const countActions = `-- name: CountActions :one
SELECT COUNT(*) FROM actions
`

func (q *Queries) CountActions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAction = `-- name: CreateAction :exec
INSERT INTO actions (id, run_id, kind, subject, actor, at, metadata_json, created_by, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO NOTHING
`

type CreateActionParams struct {
	ID           string `json:"id"`
	RunID        string `json:"run_id"`
	Kind         string `json:"kind"`
	Subject      string `json:"subject"`
	Actor        string `json:"actor"`
	At           string `json:"at"`
	MetadataJson string `json:"metadata_json"`
	CreatedBy    string `json:"created_by"`
	CreatedAt    string `json:"created_at"`
}

// Idempotent - actions are append-only and immutable once written.
func (q *Queries) CreateAction(ctx context.Context, arg CreateActionParams) error {
	_, err := q.db.ExecContext(ctx, createAction,
		arg.ID,
		arg.RunID,
		arg.Kind,
		arg.Subject,
		arg.Actor,
		arg.At,
		arg.MetadataJson,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const deleteAllActions = `-- name: DeleteAllActions :exec
DELETE FROM actions
`

func (q *Queries) DeleteAllActions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllActions)
	return err
}

const getActionByID = `-- name: GetActionByID :one
SELECT id, run_id, kind, subject, actor, at, metadata_json, created_by, created_at
FROM actions
WHERE id = ?
`

func (q *Queries) GetActionByID(ctx context.Context, id string) (Action, error) {
	row := q.db.QueryRowContext(ctx, getActionByID, id)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Kind,
		&i.Subject,
		&i.Actor,
		&i.At,
		&i.MetadataJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listActionsByRunID = `-- name: ListActionsByRunID :many
SELECT id, run_id, kind, subject, actor, at, metadata_json, created_by, created_at
FROM actions
WHERE run_id = ?
ORDER BY at ASC
`

func (q *Queries) ListActionsByRunID(ctx context.Context, runID string) ([]Action, error) {
	rows, err := q.db.QueryContext(ctx, listActionsByRunID, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Action
	for rows.Next() {
		var i Action
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Kind,
			&i.Subject,
			&i.Actor,
			&i.At,
			&i.MetadataJson,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionsBySubject = `-- name: ListActionsBySubject :many
SELECT id, run_id, kind, subject, actor, at, metadata_json, created_by, created_at
FROM actions
WHERE subject = ?
ORDER BY at ASC
`

func (q *Queries) ListActionsBySubject(ctx context.Context, subject string) ([]Action, error) {
	rows, err := q.db.QueryContext(ctx, listActionsBySubject, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Action
	for rows.Next() {
		var i Action
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Kind,
			&i.Subject,
			&i.Actor,
			&i.At,
			&i.MetadataJson,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActions = `-- name: ListAllActions :many
SELECT id, run_id, kind, subject, actor, at, metadata_json, created_by, created_at
FROM actions
ORDER BY at ASC
`

func (q *Queries) ListAllActions(ctx context.Context) ([]Action, error) {
	rows, err := q.db.QueryContext(ctx, listAllActions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Action
	for rows.Next() {
		var i Action
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Kind,
			&i.Subject,
			&i.Actor,
			&i.At,
			&i.MetadataJson,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
