// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package sqlcgen

import (
	"context"
)

const createAgent = `-- name: CreateAgent :exec
INSERT INTO agents (id, name, owner_id, scopes_json, allowed_runs_json, status, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAgentParams struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	OwnerID         string `json:"owner_id"`
	ScopesJson      string `json:"scopes_json"`
	AllowedRunsJson string `json:"allowed_runs_json"`
	Status          string `json:"status"`
	CreatedAt       string `json:"created_at"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) error {
	_, err := q.db.ExecContext(ctx, createAgent,
		arg.ID,
		arg.Name,
		arg.OwnerID,
		arg.ScopesJson,
		arg.AllowedRunsJson,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, name, owner_id, scopes_json, allowed_runs_json, status, created_at
FROM agents
WHERE id = ?
`

func (q *Queries) GetAgentByID(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.ScopesJson,
		&i.AllowedRunsJson,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, owner_id, scopes_json, allowed_runs_json, status, created_at
FROM agents
ORDER BY created_at ASC
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.ScopesJson,
			&i.AllowedRunsJson,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentAllowedRuns = `-- name: UpdateAgentAllowedRuns :exec
UPDATE agents SET allowed_runs_json = ? WHERE id = ?
`

type UpdateAgentAllowedRunsParams struct {
	AllowedRunsJson string `json:"allowed_runs_json"`
	ID              string `json:"id"`
}

func (q *Queries) UpdateAgentAllowedRuns(ctx context.Context, arg UpdateAgentAllowedRunsParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentAllowedRuns, arg.AllowedRunsJson, arg.ID)
	return err
}

const updateAgentScopes = `-- name: UpdateAgentScopes :exec
UPDATE agents SET scopes_json = ? WHERE id = ?
`

type UpdateAgentScopesParams struct {
	ScopesJson string `json:"scopes_json"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateAgentScopes(ctx context.Context, arg UpdateAgentScopesParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentScopes, arg.ScopesJson, arg.ID)
	return err
}

const updateAgentStatus = `-- name: UpdateAgentStatus :exec
UPDATE agents SET status = ? WHERE id = ?
`

type UpdateAgentStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentStatus, arg.Status, arg.ID)
	return err
}

const upsertAgent = `-- name: UpsertAgent :exec
INSERT INTO agents (id, name, owner_id, scopes_json, allowed_runs_json, status, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    owner_id = excluded.owner_id,
    scopes_json = excluded.scopes_json,
    allowed_runs_json = excluded.allowed_runs_json,
    status = excluded.status
`

type UpsertAgentParams struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	OwnerID         string `json:"owner_id"`
	ScopesJson      string `json:"scopes_json"`
	AllowedRunsJson string `json:"allowed_runs_json"`
	Status          string `json:"status"`
	CreatedAt       string `json:"created_at"`
}

func (q *Queries) UpsertAgent(ctx context.Context, arg UpsertAgentParams) error {
	_, err := q.db.ExecContext(ctx, upsertAgent,
		arg.ID,
		arg.Name,
		arg.OwnerID,
		arg.ScopesJson,
		arg.AllowedRunsJson,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}
