// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: claims.sql

package sqlcgen

import (
	"context"
)

const listAllClaims = `-- name: ListAllClaims :many
SELECT id, text, type, confidence, status, created_at, created_by
FROM claims
ORDER BY created_at ASC
`

func (q *Queries) ListAllClaims(ctx context.Context) ([]Claim, error) {
	rows, err := q.db.QueryContext(ctx, listAllClaims)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Claim
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Type,
			&i.Confidence,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertClaim = `-- name: UpsertClaim :exec
INSERT INTO claims (id, text, type, confidence, status, created_at, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  text = excluded.text,
  type = excluded.type,
  confidence = excluded.confidence,
  status = excluded.status,
  created_at = excluded.created_at,
  created_by = excluded.created_by
`

type UpsertClaimParams struct {
	ID         string  `json:"id"`
	Text       string  `json:"text"`
	Type       string  `json:"type"`
	Confidence float64 `json:"confidence"`
	Status     string  `json:"status"`
	CreatedAt  string  `json:"created_at"`
	CreatedBy  string  `json:"created_by"`
}

func (q *Queries) UpsertClaim(ctx context.Context, arg UpsertClaimParams) error {
	_, err := q.db.ExecContext(ctx, upsertClaim,
		arg.ID,
		arg.Text,
		arg.Type,
		arg.Confidence,
		arg.Status,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const upsertClaimEvidence = `-- name: UpsertClaimEvidence :exec
INSERT INTO claim_evidence (claim_id, event_id)
VALUES (?, ?)
ON CONFLICT(claim_id, event_id) DO NOTHING
`

type UpsertClaimEvidenceParams struct {
	ClaimID string `json:"claim_id"`
	EventID string `json:"event_id"`
}

func (q *Queries) UpsertClaimEvidence(ctx context.Context, arg UpsertClaimEvidenceParams) error {
	_, err := q.db.ExecContext(ctx, upsertClaimEvidence, arg.ClaimID, arg.EventID)
	return err
}
