// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: claims.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const averageTrust = `-- name: AverageTrust :one
SELECT CAST(COALESCE(AVG(trust_score), 0) AS REAL) AS avg_trust FROM claims
`

func (q *Queries) AverageTrust(ctx context.Context) (float64, error) {
	row := q.db.QueryRowContext(ctx, averageTrust)
	var avg_trust float64
	err := row.Scan(&avg_trust)
	return avg_trust, err
}

const countClaimsBelowTrust = `-- name: CountClaimsBelowTrust :one
SELECT COUNT(*) AS n FROM claims WHERE trust_score < ?
`

func (q *Queries) CountClaimsBelowTrust(ctx context.Context, trustScore float64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClaimsBelowTrust, trustScore)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const deleteAllClaimEvidence = `-- name: DeleteAllClaimEvidence :exec
DELETE FROM claim_evidence
`

func (q *Queries) DeleteAllClaimEvidence(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllClaimEvidence)
	return err
}

const deleteAllClaimStatusHistory = `-- name: DeleteAllClaimStatusHistory :exec
DELETE FROM claim_status_history
`

func (q *Queries) DeleteAllClaimStatusHistory(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllClaimStatusHistory)
	return err
}

const deleteAllClaims = `-- name: DeleteAllClaims :exec
DELETE FROM claims
`

func (q *Queries) DeleteAllClaims(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllClaims)
	return err
}

const deleteClaimByID = `-- name: DeleteClaimByID :exec
DELETE FROM claims WHERE id = ?
`

func (q *Queries) DeleteClaimByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteClaimByID, id)
	return err
}

const deleteClaimEvidenceByClaimID = `-- name: DeleteClaimEvidenceByClaimID :exec
DELETE FROM claim_evidence WHERE claim_id = ?
`

func (q *Queries) DeleteClaimEvidenceByClaimID(ctx context.Context, claimID string) error {
	_, err := q.db.ExecContext(ctx, deleteClaimEvidenceByClaimID, claimID)
	return err
}

const deleteClaimStatusHistoryByClaimID = `-- name: DeleteClaimStatusHistoryByClaimID :exec
DELETE FROM claim_status_history WHERE claim_id = ?
`

func (q *Queries) DeleteClaimStatusHistoryByClaimID(ctx context.Context, claimID string) error {
	_, err := q.db.ExecContext(ctx, deleteClaimStatusHistoryByClaimID, claimID)
	return err
}

const listAllClaims = `-- name: ListAllClaims :many
SELECT id, text, type, confidence, status, created_at, created_by, trust_score,
       valid_from, valid_to
FROM claims
ORDER BY created_at ASC
`

func (q *Queries) ListAllClaims(ctx context.Context) ([]Claim, error) {
	rows, err := q.db.QueryContext(ctx, listAllClaims)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Claim
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Type,
			&i.Confidence,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.TrustScore,
			&i.ValidFrom,
			&i.ValidTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaimTrustInputs = `-- name: ListClaimTrustInputs :many
SELECT
  c.id              AS claim_id,
  c.confidence      AS confidence,
  COUNT(DISTINCT ce.event_id) AS evidence_count,
  CAST(COALESCE(MAX(e.timestamp), '') AS TEXT) AS latest_evidence_at
FROM claims c
LEFT JOIN claim_evidence ce ON ce.claim_id = c.id
LEFT JOIN events e          ON e.id = ce.event_id
GROUP BY c.id, c.confidence
`

type ListClaimTrustInputsRow struct {
	ClaimID          string  `json:"claim_id"`
	Confidence       float64 `json:"confidence"`
	EvidenceCount    int64   `json:"evidence_count"`
	LatestEvidenceAt string  `json:"latest_evidence_at"`
}

// Inputs to recompute trust_score for every claim: confidence, the
// distinct evidence-event count, and the most-recent evidence event
// timestamp. LEFT JOIN so claims with no evidence still appear; the
// caller treats the missing aggregate as 0/empty.
func (q *Queries) ListClaimTrustInputs(ctx context.Context) ([]ListClaimTrustInputsRow, error) {
	rows, err := q.db.QueryContext(ctx, listClaimTrustInputs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClaimTrustInputsRow
	for rows.Next() {
		var i ListClaimTrustInputsRow
		if err := rows.Scan(
			&i.ClaimID,
			&i.Confidence,
			&i.EvidenceCount,
			&i.LatestEvidenceAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setClaimValidity = `-- name: SetClaimValidity :exec
UPDATE claims SET valid_to = ? WHERE id = ?
`

type SetClaimValidityParams struct {
	ValidTo sql.NullString `json:"valid_to"`
	ID      string         `json:"id"`
}

// Atomic supersession primitive: mark a claim as no longer valid as
// of the given timestamp. Pass NULL to clear valid_to (un-supersede
// the claim), useful when a resolution is reverted.
func (q *Queries) SetClaimValidity(ctx context.Context, arg SetClaimValidityParams) error {
	_, err := q.db.ExecContext(ctx, setClaimValidity, arg.ValidTo, arg.ID)
	return err
}

const updateClaimTrust = `-- name: UpdateClaimTrust :exec
UPDATE claims SET trust_score = ? WHERE id = ?
`

type UpdateClaimTrustParams struct {
	TrustScore float64 `json:"trust_score"`
	ID         string  `json:"id"`
}

func (q *Queries) UpdateClaimTrust(ctx context.Context, arg UpdateClaimTrustParams) error {
	_, err := q.db.ExecContext(ctx, updateClaimTrust, arg.TrustScore, arg.ID)
	return err
}

const upsertClaim = `-- name: UpsertClaim :exec
INSERT INTO claims (id, text, type, confidence, status, created_at, created_by, valid_from)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  text = excluded.text,
  type = excluded.type,
  confidence = excluded.confidence,
  status = excluded.status,
  created_at = excluded.created_at,
  created_by = excluded.created_by,
  valid_from = excluded.valid_from
`

type UpsertClaimParams struct {
	ID         string  `json:"id"`
	Text       string  `json:"text"`
	Type       string  `json:"type"`
	Confidence float64 `json:"confidence"`
	Status     string  `json:"status"`
	CreatedAt  string  `json:"created_at"`
	CreatedBy  string  `json:"created_by"`
	ValidFrom  string  `json:"valid_from"`
}

// ON CONFLICT preserves trust_score and valid_to (computed/managed
// separately via UpdateClaimTrust and SetClaimValidity), but does
// refresh valid_from: re-extracting a claim with newer evidence is
// a legitimate "this fact is observed again from <ts>" signal.
func (q *Queries) UpsertClaim(ctx context.Context, arg UpsertClaimParams) error {
	_, err := q.db.ExecContext(ctx, upsertClaim,
		arg.ID,
		arg.Text,
		arg.Type,
		arg.Confidence,
		arg.Status,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.ValidFrom,
	)
	return err
}

const upsertClaimEvidence = `-- name: UpsertClaimEvidence :exec
INSERT INTO claim_evidence (claim_id, event_id)
VALUES (?, ?)
ON CONFLICT(claim_id, event_id) DO NOTHING
`

type UpsertClaimEvidenceParams struct {
	ClaimID string `json:"claim_id"`
	EventID string `json:"event_id"`
}

func (q *Queries) UpsertClaimEvidence(ctx context.Context, arg UpsertClaimEvidenceParams) error {
	_, err := q.db.ExecContext(ctx, upsertClaimEvidence, arg.ClaimID, arg.EventID)
	return err
}
