// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: compilation_jobs.sql

package sqlcgen

import (
	"context"
)

const getCompilationJobByID = `-- name: GetCompilationJobByID :one
SELECT id, kind, status, scope_json, started_at, updated_at, error
FROM compilation_jobs
WHERE id = ?
`

func (q *Queries) GetCompilationJobByID(ctx context.Context, id string) (CompilationJob, error) {
	row := q.db.QueryRowContext(ctx, getCompilationJobByID, id)
	var i CompilationJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.ScopeJson,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.Error,
	)
	return i, err
}

const upsertCompilationJob = `-- name: UpsertCompilationJob :exec
INSERT INTO compilation_jobs (id, kind, status, scope_json, started_at, updated_at, error)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  kind = excluded.kind,
  status = excluded.status,
  scope_json = excluded.scope_json,
  started_at = excluded.started_at,
  updated_at = excluded.updated_at,
  error = excluded.error
`

type UpsertCompilationJobParams struct {
	ID        string `json:"id"`
	Kind      string `json:"kind"`
	Status    string `json:"status"`
	ScopeJson string `json:"scope_json"`
	StartedAt string `json:"started_at"`
	UpdatedAt string `json:"updated_at"`
	Error     string `json:"error"`
}

func (q *Queries) UpsertCompilationJob(ctx context.Context, arg UpsertCompilationJobParams) error {
	_, err := q.db.ExecContext(ctx, upsertCompilationJob,
		arg.ID,
		arg.Kind,
		arg.Status,
		arg.ScopeJson,
		arg.StartedAt,
		arg.UpdatedAt,
		arg.Error,
	)
	return err
}
