// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: embeddings.sql

package sqlcgen

import (
	"context"
)

const getEmbeddingByEntityID = `-- name: GetEmbeddingByEntityID :one
SELECT entity_id, entity_type, vector, model, dimensions, created_at
FROM embeddings
WHERE entity_id = ? AND entity_type = ?
`

type GetEmbeddingByEntityIDParams struct {
	EntityID   string `json:"entity_id"`
	EntityType string `json:"entity_type"`
}

func (q *Queries) GetEmbeddingByEntityID(ctx context.Context, arg GetEmbeddingByEntityIDParams) (Embedding, error) {
	row := q.db.QueryRowContext(ctx, getEmbeddingByEntityID, arg.EntityID, arg.EntityType)
	var i Embedding
	err := row.Scan(
		&i.EntityID,
		&i.EntityType,
		&i.Vector,
		&i.Model,
		&i.Dimensions,
		&i.CreatedAt,
	)
	return i, err
}

const listEmbeddingsByEntityType = `-- name: ListEmbeddingsByEntityType :many
SELECT entity_id, entity_type, vector, model, dimensions, created_at
FROM embeddings
WHERE entity_type = ?
ORDER BY created_at ASC
`

func (q *Queries) ListEmbeddingsByEntityType(ctx context.Context, entityType string) ([]Embedding, error) {
	rows, err := q.db.QueryContext(ctx, listEmbeddingsByEntityType, entityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Embedding
	for rows.Next() {
		var i Embedding
		if err := rows.Scan(
			&i.EntityID,
			&i.EntityType,
			&i.Vector,
			&i.Model,
			&i.Dimensions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEmbedding = `-- name: UpsertEmbedding :exec
INSERT INTO embeddings (entity_id, entity_type, vector, model, dimensions, created_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (entity_id, entity_type) DO UPDATE SET
  vector = excluded.vector,
  model = excluded.model,
  dimensions = excluded.dimensions,
  created_at = excluded.created_at
`

type UpsertEmbeddingParams struct {
	EntityID   string `json:"entity_id"`
	EntityType string `json:"entity_type"`
	Vector     []byte `json:"vector"`
	Model      string `json:"model"`
	Dimensions int64  `json:"dimensions"`
	CreatedAt  string `json:"created_at"`
}

func (q *Queries) UpsertEmbedding(ctx context.Context, arg UpsertEmbeddingParams) error {
	_, err := q.db.ExecContext(ctx, upsertEmbedding,
		arg.EntityID,
		arg.EntityType,
		arg.Vector,
		arg.Model,
		arg.Dimensions,
		arg.CreatedAt,
	)
	return err
}
