// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: embeddings.sql

package sqlcgen

import (
	"context"
)

const deleteAllEmbeddings = `-- name: DeleteAllEmbeddings :exec
DELETE FROM embeddings
`

func (q *Queries) DeleteAllEmbeddings(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllEmbeddings)
	return err
}

const deleteEmbeddingByEntity = `-- name: DeleteEmbeddingByEntity :exec
DELETE FROM embeddings WHERE entity_id = ? AND entity_type = ?
`

type DeleteEmbeddingByEntityParams struct {
	EntityID   string `json:"entity_id"`
	EntityType string `json:"entity_type"`
}

func (q *Queries) DeleteEmbeddingByEntity(ctx context.Context, arg DeleteEmbeddingByEntityParams) error {
	_, err := q.db.ExecContext(ctx, deleteEmbeddingByEntity, arg.EntityID, arg.EntityType)
	return err
}

const deleteEmbeddingsByEntityType = `-- name: DeleteEmbeddingsByEntityType :exec
DELETE FROM embeddings WHERE entity_type = ?
`

func (q *Queries) DeleteEmbeddingsByEntityType(ctx context.Context, entityType string) error {
	_, err := q.db.ExecContext(ctx, deleteEmbeddingsByEntityType, entityType)
	return err
}

const getEmbeddingByEntityID = `-- name: GetEmbeddingByEntityID :one
SELECT entity_id, entity_type, vector, model, dimensions, created_at, created_by
FROM embeddings
WHERE entity_id = ? AND entity_type = ?
`

type GetEmbeddingByEntityIDParams struct {
	EntityID   string `json:"entity_id"`
	EntityType string `json:"entity_type"`
}

func (q *Queries) GetEmbeddingByEntityID(ctx context.Context, arg GetEmbeddingByEntityIDParams) (Embedding, error) {
	row := q.db.QueryRowContext(ctx, getEmbeddingByEntityID, arg.EntityID, arg.EntityType)
	var i Embedding
	err := row.Scan(
		&i.EntityID,
		&i.EntityType,
		&i.Vector,
		&i.Model,
		&i.Dimensions,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listEmbeddingsByEntityType = `-- name: ListEmbeddingsByEntityType :many
SELECT entity_id, entity_type, vector, model, dimensions, created_at, created_by
FROM embeddings
WHERE entity_type = ?
ORDER BY created_at ASC
`

func (q *Queries) ListEmbeddingsByEntityType(ctx context.Context, entityType string) ([]Embedding, error) {
	rows, err := q.db.QueryContext(ctx, listEmbeddingsByEntityType, entityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Embedding
	for rows.Next() {
		var i Embedding
		if err := rows.Scan(
			&i.EntityID,
			&i.EntityType,
			&i.Vector,
			&i.Model,
			&i.Dimensions,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityIDsMissingEmbedding = `-- name: ListEntityIDsMissingEmbedding :many
SELECT id FROM claims
WHERE id NOT IN (SELECT entity_id FROM embeddings WHERE entity_type = 'claim')
ORDER BY created_at ASC
`

// Returns claim ids that don't yet have an embedding (entity_type='claim').
func (q *Queries) ListEntityIDsMissingEmbedding(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listEntityIDsMissingEmbedding)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEmbedding = `-- name: UpsertEmbedding :exec
INSERT INTO embeddings (entity_id, entity_type, vector, model, dimensions, created_at, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (entity_id, entity_type) DO UPDATE SET
  vector = excluded.vector,
  model = excluded.model,
  dimensions = excluded.dimensions,
  created_at = excluded.created_at,
  created_by = excluded.created_by
`

type UpsertEmbeddingParams struct {
	EntityID   string `json:"entity_id"`
	EntityType string `json:"entity_type"`
	Vector     []byte `json:"vector"`
	Model      string `json:"model"`
	Dimensions int64  `json:"dimensions"`
	CreatedAt  string `json:"created_at"`
	CreatedBy  string `json:"created_by"`
}

func (q *Queries) UpsertEmbedding(ctx context.Context, arg UpsertEmbeddingParams) error {
	_, err := q.db.ExecContext(ctx, upsertEmbedding,
		arg.EntityID,
		arg.EntityType,
		arg.Vector,
		arg.Model,
		arg.Dimensions,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}
