// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entity_relationships.sql

package sqlcgen

import (
	"context"
)

const countEntityRelationships = `-- name: CountEntityRelationships :one
SELECT COUNT(*) FROM entity_relationships
`

func (q *Queries) CountEntityRelationships(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEntityRelationships)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllEntityRelationships = `-- name: DeleteAllEntityRelationships :exec
DELETE FROM entity_relationships
`

func (q *Queries) DeleteAllEntityRelationships(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllEntityRelationships)
	return err
}

const listEntityRelationships = `-- name: ListEntityRelationships :many
SELECT id, kind, from_id, from_type, to_id, to_type, created_at, created_by
FROM entity_relationships
ORDER BY created_at ASC
`

func (q *Queries) ListEntityRelationships(ctx context.Context) ([]EntityRelationship, error) {
	rows, err := q.db.QueryContext(ctx, listEntityRelationships)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityRelationship
	for rows.Next() {
		var i EntityRelationship
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.FromID,
			&i.FromType,
			&i.ToID,
			&i.ToType,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityRelationshipsByEntity = `-- name: ListEntityRelationshipsByEntity :many
SELECT id, kind, from_id, from_type, to_id, to_type, created_at, created_by
FROM entity_relationships
WHERE (from_id = ?1 AND from_type = ?2) OR (to_id = ?1 AND to_type = ?2)
ORDER BY created_at ASC
`

type ListEntityRelationshipsByEntityParams struct {
	FromID   string `json:"from_id"`
	FromType string `json:"from_type"`
}

func (q *Queries) ListEntityRelationshipsByEntity(ctx context.Context, arg ListEntityRelationshipsByEntityParams) ([]EntityRelationship, error) {
	rows, err := q.db.QueryContext(ctx, listEntityRelationshipsByEntity, arg.FromID, arg.FromType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityRelationship
	for rows.Next() {
		var i EntityRelationship
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.FromID,
			&i.FromType,
			&i.ToID,
			&i.ToType,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityRelationshipsByKind = `-- name: ListEntityRelationshipsByKind :many
SELECT id, kind, from_id, from_type, to_id, to_type, created_at, created_by
FROM entity_relationships
WHERE kind = ?
ORDER BY created_at ASC
`

func (q *Queries) ListEntityRelationshipsByKind(ctx context.Context, kind string) ([]EntityRelationship, error) {
	rows, err := q.db.QueryContext(ctx, listEntityRelationshipsByKind, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityRelationship
	for rows.Next() {
		var i EntityRelationship
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.FromID,
			&i.FromType,
			&i.ToID,
			&i.ToType,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEntityRelationship = `-- name: UpsertEntityRelationship :exec
INSERT INTO entity_relationships (id, kind, from_id, from_type, to_id, to_type, created_at, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(kind, from_type, from_id, to_type, to_id) DO NOTHING
`

type UpsertEntityRelationshipParams struct {
	ID        string `json:"id"`
	Kind      string `json:"kind"`
	FromID    string `json:"from_id"`
	FromType  string `json:"from_type"`
	ToID      string `json:"to_id"`
	ToType    string `json:"to_type"`
	CreatedAt string `json:"created_at"`
	CreatedBy string `json:"created_by"`
}

func (q *Queries) UpsertEntityRelationship(ctx context.Context, arg UpsertEntityRelationshipParams) error {
	_, err := q.db.ExecContext(ctx, upsertEntityRelationship,
		arg.ID,
		arg.Kind,
		arg.FromID,
		arg.FromType,
		arg.ToID,
		arg.ToType,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}
