// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entities.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const claimIDsMissingEntityLinks = `-- name: ClaimIDsMissingEntityLinks :many
SELECT id FROM claims
WHERE id NOT IN (SELECT DISTINCT claim_id FROM claim_entities)
ORDER BY created_at ASC
`

// Used by `mnemos extract-entities` to find claims that have no entity
// links yet (post v0.9 backfill candidates).
func (q *Queries) ClaimIDsMissingEntityLinks(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, claimIDsMissingEntityLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countEntities = `-- name: CountEntities :one
SELECT COUNT(*) AS n FROM entities
`

func (q *Queries) CountEntities(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEntities)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const deleteClaimEntitiesByClaimID = `-- name: DeleteClaimEntitiesByClaimID :exec
DELETE FROM claim_entities WHERE claim_id = ?
`

func (q *Queries) DeleteClaimEntitiesByClaimID(ctx context.Context, claimID string) error {
	_, err := q.db.ExecContext(ctx, deleteClaimEntitiesByClaimID, claimID)
	return err
}

const deleteClaimEntitiesByEntityID = `-- name: DeleteClaimEntitiesByEntityID :exec
DELETE FROM claim_entities WHERE entity_id = ?
`

func (q *Queries) DeleteClaimEntitiesByEntityID(ctx context.Context, entityID string) error {
	_, err := q.db.ExecContext(ctx, deleteClaimEntitiesByEntityID, entityID)
	return err
}

const deleteEntityByID = `-- name: DeleteEntityByID :exec
DELETE FROM entities WHERE id = ?
`

func (q *Queries) DeleteEntityByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEntityByID, id)
	return err
}

const findEntityByNormalizedName = `-- name: FindEntityByNormalizedName :one
SELECT id, name, normalized_name, type, created_at, created_by
FROM entities
WHERE normalized_name = ? AND type = ?
`

type FindEntityByNormalizedNameParams struct {
	NormalizedName string `json:"normalized_name"`
	Type           string `json:"type"`
}

func (q *Queries) FindEntityByNormalizedName(ctx context.Context, arg FindEntityByNormalizedNameParams) (Entity, error) {
	row := q.db.QueryRowContext(ctx, findEntityByNormalizedName, arg.NormalizedName, arg.Type)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.Type,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getEntityByID = `-- name: GetEntityByID :one
SELECT id, name, normalized_name, type, created_at, created_by
FROM entities
WHERE id = ?
`

func (q *Queries) GetEntityByID(ctx context.Context, id string) (Entity, error) {
	row := q.db.QueryRowContext(ctx, getEntityByID, id)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.Type,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listClaimsByEntityID = `-- name: ListClaimsByEntityID :many
SELECT c.id, c.text, c.type, c.confidence, c.status, c.created_at, c.created_by, c.trust_score, c.valid_from, c.valid_to
FROM claims c
JOIN claim_entities ce ON ce.claim_id = c.id
WHERE ce.entity_id = ?
ORDER BY c.created_at ASC
`

type ListClaimsByEntityIDRow struct {
	ID         string         `json:"id"`
	Text       string         `json:"text"`
	Type       string         `json:"type"`
	Confidence float64        `json:"confidence"`
	Status     string         `json:"status"`
	CreatedAt  string         `json:"created_at"`
	CreatedBy  string         `json:"created_by"`
	TrustScore float64        `json:"trust_score"`
	ValidFrom  string         `json:"valid_from"`
	ValidTo    sql.NullString `json:"valid_to"`
}

func (q *Queries) ListClaimsByEntityID(ctx context.Context, entityID string) ([]ListClaimsByEntityIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listClaimsByEntityID, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClaimsByEntityIDRow
	for rows.Next() {
		var i ListClaimsByEntityIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Type,
			&i.Confidence,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.TrustScore,
			&i.ValidFrom,
			&i.ValidTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntities = `-- name: ListEntities :many
SELECT id, name, normalized_name, type, created_at, created_by
FROM entities
ORDER BY name ASC
`

func (q *Queries) ListEntities(ctx context.Context) ([]Entity, error) {
	rows, err := q.db.QueryContext(ctx, listEntities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entity
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NormalizedName,
			&i.Type,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntitiesByClaimID = `-- name: ListEntitiesByClaimID :many
SELECT e.id, e.name, e.normalized_name, e.type, e.created_at, e.created_by, ce.role
FROM entities e
JOIN claim_entities ce ON ce.entity_id = e.id
WHERE ce.claim_id = ?
ORDER BY e.name ASC
`

type ListEntitiesByClaimIDRow struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	NormalizedName string `json:"normalized_name"`
	Type           string `json:"type"`
	CreatedAt      string `json:"created_at"`
	CreatedBy      string `json:"created_by"`
	Role           string `json:"role"`
}

func (q *Queries) ListEntitiesByClaimID(ctx context.Context, claimID string) ([]ListEntitiesByClaimIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntitiesByClaimID, claimID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntitiesByClaimIDRow
	for rows.Next() {
		var i ListEntitiesByClaimIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NormalizedName,
			&i.Type,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntitiesByType = `-- name: ListEntitiesByType :many
SELECT id, name, normalized_name, type, created_at, created_by
FROM entities
WHERE type = ?
ORDER BY name ASC
`

func (q *Queries) ListEntitiesByType(ctx context.Context, type_ string) ([]Entity, error) {
	rows, err := q.db.QueryContext(ctx, listEntitiesByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entity
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NormalizedName,
			&i.Type,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignClaimEntitiesEntity = `-- name: ReassignClaimEntitiesEntity :exec
INSERT OR IGNORE INTO claim_entities (claim_id, entity_id, role)
SELECT ce.claim_id, ?, ce.role FROM claim_entities ce WHERE ce.entity_id = ?
`

type ReassignClaimEntitiesEntityParams struct {
	EntityID   string `json:"entity_id"`
	EntityID_2 string `json:"entity_id_2"`
}

// Used by entity merge: redirect every claim_entities row from the
// losing entity to the winner. INSERT OR IGNORE prevents the unique
// constraint from firing when both entities already linked the same
// claim under the same role.
func (q *Queries) ReassignClaimEntitiesEntity(ctx context.Context, arg ReassignClaimEntitiesEntityParams) error {
	_, err := q.db.ExecContext(ctx, reassignClaimEntitiesEntity, arg.EntityID, arg.EntityID_2)
	return err
}

const searchEntitiesByNamePrefix = `-- name: SearchEntitiesByNamePrefix :many
SELECT id, name, normalized_name, type, created_at, created_by
FROM entities
WHERE normalized_name LIKE CAST(? AS TEXT) || '%'
ORDER BY name ASC
`

func (q *Queries) SearchEntitiesByNamePrefix(ctx context.Context, dollar_1 string) ([]Entity, error) {
	rows, err := q.db.QueryContext(ctx, searchEntitiesByNamePrefix, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entity
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NormalizedName,
			&i.Type,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertClaimEntity = `-- name: UpsertClaimEntity :exec
INSERT INTO claim_entities (claim_id, entity_id, role)
VALUES (?, ?, ?)
ON CONFLICT(claim_id, entity_id, role) DO NOTHING
`

type UpsertClaimEntityParams struct {
	ClaimID  string `json:"claim_id"`
	EntityID string `json:"entity_id"`
	Role     string `json:"role"`
}

func (q *Queries) UpsertClaimEntity(ctx context.Context, arg UpsertClaimEntityParams) error {
	_, err := q.db.ExecContext(ctx, upsertClaimEntity, arg.ClaimID, arg.EntityID, arg.Role)
	return err
}

const upsertEntity = `-- name: UpsertEntity :exec
INSERT INTO entities (id, name, normalized_name, type, created_at, created_by)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(normalized_name, type) DO NOTHING
`

type UpsertEntityParams struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	NormalizedName string `json:"normalized_name"`
	Type           string `json:"type"`
	CreatedAt      string `json:"created_at"`
	CreatedBy      string `json:"created_by"`
}

// Insert a new entity or noop if (normalized_name, type) already exists.
// The id is supplied by the caller so concurrent insert races still hit
// the UNIQUE constraint and DO NOTHING; FindEntityByNormalizedName then
// returns the canonical row.
func (q *Queries) UpsertEntity(ctx context.Context, arg UpsertEntityParams) error {
	_, err := q.db.ExecContext(ctx, upsertEntity,
		arg.ID,
		arg.Name,
		arg.NormalizedName,
		arg.Type,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}
