// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlcgen

import (
	"context"
)

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (id, run_id, schema_version, content, source_input_id, timestamp, metadata_json, ingested_at, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO NOTHING
`

type CreateEventParams struct {
	ID            string `json:"id"`
	RunID         string `json:"run_id"`
	SchemaVersion string `json:"schema_version"`
	Content       string `json:"content"`
	SourceInputID string `json:"source_input_id"`
	Timestamp     string `json:"timestamp"`
	MetadataJson  string `json:"metadata_json"`
	IngestedAt    string `json:"ingested_at"`
	CreatedBy     string `json:"created_by"`
}

// Idempotent so retried pushes (and re-runs of best-effort
// pipelines) don't fail with PRIMARY KEY constraint violations.
// Events are append-only by domain contract; once an id is in the
// table its content is fixed, so the conflict path is a no-op.
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.ExecContext(ctx, createEvent,
		arg.ID,
		arg.RunID,
		arg.SchemaVersion,
		arg.Content,
		arg.SourceInputID,
		arg.Timestamp,
		arg.MetadataJson,
		arg.IngestedAt,
		arg.CreatedBy,
	)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, run_id, schema_version, content, source_input_id, timestamp, metadata_json, ingested_at, created_by
FROM events
WHERE id = ?
`

func (q *Queries) GetEventByID(ctx context.Context, id string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.SchemaVersion,
		&i.Content,
		&i.SourceInputID,
		&i.Timestamp,
		&i.MetadataJson,
		&i.IngestedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listAllEvents = `-- name: ListAllEvents :many
SELECT id, run_id, schema_version, content, source_input_id, timestamp, metadata_json, ingested_at, created_by
FROM events
ORDER BY timestamp ASC
`

func (q *Queries) ListAllEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listAllEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.SchemaVersion,
			&i.Content,
			&i.SourceInputID,
			&i.Timestamp,
			&i.MetadataJson,
			&i.IngestedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByRunID = `-- name: ListEventsByRunID :many
SELECT id, run_id, schema_version, content, source_input_id, timestamp, metadata_json, ingested_at, created_by
FROM events
WHERE run_id = ?
ORDER BY timestamp ASC
`

func (q *Queries) ListEventsByRunID(ctx context.Context, runID string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByRunID, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.SchemaVersion,
			&i.Content,
			&i.SourceInputID,
			&i.Timestamp,
			&i.MetadataJson,
			&i.IngestedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
