// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlcgen

import (
	"context"
)

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (id, schema_version, content, source_input_id, timestamp, metadata_json, ingested_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateEventParams struct {
	ID            string `json:"id"`
	SchemaVersion string `json:"schema_version"`
	Content       string `json:"content"`
	SourceInputID string `json:"source_input_id"`
	Timestamp     string `json:"timestamp"`
	MetadataJson  string `json:"metadata_json"`
	IngestedAt    string `json:"ingested_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.ExecContext(ctx, createEvent,
		arg.ID,
		arg.SchemaVersion,
		arg.Content,
		arg.SourceInputID,
		arg.Timestamp,
		arg.MetadataJson,
		arg.IngestedAt,
	)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, schema_version, content, source_input_id, timestamp, metadata_json, ingested_at
FROM events
WHERE id = ?
`

func (q *Queries) GetEventByID(ctx context.Context, id string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.SchemaVersion,
		&i.Content,
		&i.SourceInputID,
		&i.Timestamp,
		&i.MetadataJson,
		&i.IngestedAt,
	)
	return i, err
}

const listAllEvents = `-- name: ListAllEvents :many
SELECT id, schema_version, content, source_input_id, timestamp, metadata_json, ingested_at
FROM events
ORDER BY timestamp ASC
`

func (q *Queries) ListAllEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listAllEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SchemaVersion,
			&i.Content,
			&i.SourceInputID,
			&i.Timestamp,
			&i.MetadataJson,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
