// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

type Claim struct {
	ID         string  `json:"id"`
	Text       string  `json:"text"`
	Type       string  `json:"type"`
	Confidence float64 `json:"confidence"`
	Status     string  `json:"status"`
	CreatedAt  string  `json:"created_at"`
}

type ClaimEvidence struct {
	ClaimID string `json:"claim_id"`
	EventID string `json:"event_id"`
}

type CompilationJob struct {
	ID        string `json:"id"`
	Kind      string `json:"kind"`
	Status    string `json:"status"`
	ScopeJson string `json:"scope_json"`
	StartedAt string `json:"started_at"`
	UpdatedAt string `json:"updated_at"`
	Error     string `json:"error"`
}

type Event struct {
	ID            string `json:"id"`
	SchemaVersion string `json:"schema_version"`
	Content       string `json:"content"`
	SourceInputID string `json:"source_input_id"`
	Timestamp     string `json:"timestamp"`
	MetadataJson  string `json:"metadata_json"`
	IngestedAt    string `json:"ingested_at"`
}

type Relationship struct {
	ID          string `json:"id"`
	Type        string `json:"type"`
	FromClaimID string `json:"from_claim_id"`
	ToClaimID   string `json:"to_claim_id"`
	CreatedAt   string `json:"created_at"`
}
