// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outcomes.sql

package sqlcgen

import (
	"context"
)

const countOutcomes = `-- name: CountOutcomes :one
SELECT COUNT(*) FROM outcomes
`

func (q *Queries) CountOutcomes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOutcomes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOutcome = `-- name: CreateOutcome :exec
INSERT INTO outcomes (id, action_id, result, metrics_json, notes, observed_at, source, created_by, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO NOTHING
`

type CreateOutcomeParams struct {
	ID          string `json:"id"`
	ActionID    string `json:"action_id"`
	Result      string `json:"result"`
	MetricsJson string `json:"metrics_json"`
	Notes       string `json:"notes"`
	ObservedAt  string `json:"observed_at"`
	Source      string `json:"source"`
	CreatedBy   string `json:"created_by"`
	CreatedAt   string `json:"created_at"`
}

// Idempotent - outcomes are append-only.
func (q *Queries) CreateOutcome(ctx context.Context, arg CreateOutcomeParams) error {
	_, err := q.db.ExecContext(ctx, createOutcome,
		arg.ID,
		arg.ActionID,
		arg.Result,
		arg.MetricsJson,
		arg.Notes,
		arg.ObservedAt,
		arg.Source,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const deleteAllOutcomes = `-- name: DeleteAllOutcomes :exec
DELETE FROM outcomes
`

func (q *Queries) DeleteAllOutcomes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllOutcomes)
	return err
}

const getOutcomeByID = `-- name: GetOutcomeByID :one
SELECT id, action_id, result, metrics_json, notes, observed_at, source, created_by, created_at
FROM outcomes
WHERE id = ?
`

func (q *Queries) GetOutcomeByID(ctx context.Context, id string) (Outcome, error) {
	row := q.db.QueryRowContext(ctx, getOutcomeByID, id)
	var i Outcome
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.Result,
		&i.MetricsJson,
		&i.Notes,
		&i.ObservedAt,
		&i.Source,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAllOutcomes = `-- name: ListAllOutcomes :many
SELECT id, action_id, result, metrics_json, notes, observed_at, source, created_by, created_at
FROM outcomes
ORDER BY observed_at ASC
`

func (q *Queries) ListAllOutcomes(ctx context.Context) ([]Outcome, error) {
	rows, err := q.db.QueryContext(ctx, listAllOutcomes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outcome
	for rows.Next() {
		var i Outcome
		if err := rows.Scan(
			&i.ID,
			&i.ActionID,
			&i.Result,
			&i.MetricsJson,
			&i.Notes,
			&i.ObservedAt,
			&i.Source,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutcomesByActionID = `-- name: ListOutcomesByActionID :many
SELECT id, action_id, result, metrics_json, notes, observed_at, source, created_by, created_at
FROM outcomes
WHERE action_id = ?
ORDER BY observed_at ASC
`

func (q *Queries) ListOutcomesByActionID(ctx context.Context, actionID string) ([]Outcome, error) {
	rows, err := q.db.QueryContext(ctx, listOutcomesByActionID, actionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outcome
	for rows.Next() {
		var i Outcome
		if err := rows.Scan(
			&i.ID,
			&i.ActionID,
			&i.Result,
			&i.MetricsJson,
			&i.Notes,
			&i.ObservedAt,
			&i.Source,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
