// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playbooks.sql

package sqlcgen

import (
	"context"
)

const appendPlaybookLesson = `-- name: AppendPlaybookLesson :exec
INSERT INTO playbook_lessons (playbook_id, lesson_id)
VALUES (?, ?)
ON CONFLICT(playbook_id, lesson_id) DO NOTHING
`

type AppendPlaybookLessonParams struct {
	PlaybookID string `json:"playbook_id"`
	LessonID   string `json:"lesson_id"`
}

func (q *Queries) AppendPlaybookLesson(ctx context.Context, arg AppendPlaybookLessonParams) error {
	_, err := q.db.ExecContext(ctx, appendPlaybookLesson, arg.PlaybookID, arg.LessonID)
	return err
}

const countPlaybooks = `-- name: CountPlaybooks :one
SELECT COUNT(*) FROM playbooks
`

func (q *Queries) CountPlaybooks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlaybooks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlaybook = `-- name: CreatePlaybook :exec
INSERT INTO playbooks (id, trigger, statement, scope_service, scope_env, scope_team, steps_json, confidence, derived_at, last_verified, source, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  trigger = excluded.trigger,
  statement = excluded.statement,
  steps_json = excluded.steps_json,
  confidence = excluded.confidence,
  derived_at = excluded.derived_at,
  last_verified = excluded.last_verified
`

type CreatePlaybookParams struct {
	ID           string  `json:"id"`
	Trigger      string  `json:"trigger"`
	Statement    string  `json:"statement"`
	ScopeService string  `json:"scope_service"`
	ScopeEnv     string  `json:"scope_env"`
	ScopeTeam    string  `json:"scope_team"`
	StepsJson    string  `json:"steps_json"`
	Confidence   float64 `json:"confidence"`
	DerivedAt    string  `json:"derived_at"`
	LastVerified string  `json:"last_verified"`
	Source       string  `json:"source"`
	CreatedBy    string  `json:"created_by"`
}

// Idempotent on id; UPSERT refreshes statement, steps, confidence,
// derived_at, last_verified so re-synthesis ratchets identity-stably.
func (q *Queries) CreatePlaybook(ctx context.Context, arg CreatePlaybookParams) error {
	_, err := q.db.ExecContext(ctx, createPlaybook,
		arg.ID,
		arg.Trigger,
		arg.Statement,
		arg.ScopeService,
		arg.ScopeEnv,
		arg.ScopeTeam,
		arg.StepsJson,
		arg.Confidence,
		arg.DerivedAt,
		arg.LastVerified,
		arg.Source,
		arg.CreatedBy,
	)
	return err
}

const deleteAllPlaybookLessons = `-- name: DeleteAllPlaybookLessons :exec
DELETE FROM playbook_lessons
`

func (q *Queries) DeleteAllPlaybookLessons(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllPlaybookLessons)
	return err
}

const deleteAllPlaybooks = `-- name: DeleteAllPlaybooks :exec
DELETE FROM playbooks
`

func (q *Queries) DeleteAllPlaybooks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllPlaybooks)
	return err
}

const getPlaybookByID = `-- name: GetPlaybookByID :one
SELECT id, trigger, statement, scope_service, scope_env, scope_team, steps_json, confidence, derived_at, last_verified, source, created_by
FROM playbooks
WHERE id = ?
`

func (q *Queries) GetPlaybookByID(ctx context.Context, id string) (Playbook, error) {
	row := q.db.QueryRowContext(ctx, getPlaybookByID, id)
	var i Playbook
	err := row.Scan(
		&i.ID,
		&i.Trigger,
		&i.Statement,
		&i.ScopeService,
		&i.ScopeEnv,
		&i.ScopeTeam,
		&i.StepsJson,
		&i.Confidence,
		&i.DerivedAt,
		&i.LastVerified,
		&i.Source,
		&i.CreatedBy,
	)
	return i, err
}

const listAllPlaybooks = `-- name: ListAllPlaybooks :many
SELECT id, trigger, statement, scope_service, scope_env, scope_team, steps_json, confidence, derived_at, last_verified, source, created_by
FROM playbooks
ORDER BY confidence DESC, derived_at DESC
`

func (q *Queries) ListAllPlaybooks(ctx context.Context) ([]Playbook, error) {
	rows, err := q.db.QueryContext(ctx, listAllPlaybooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playbook
	for rows.Next() {
		var i Playbook
		if err := rows.Scan(
			&i.ID,
			&i.Trigger,
			&i.Statement,
			&i.ScopeService,
			&i.ScopeEnv,
			&i.ScopeTeam,
			&i.StepsJson,
			&i.Confidence,
			&i.DerivedAt,
			&i.LastVerified,
			&i.Source,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaybookLessons = `-- name: ListPlaybookLessons :many
SELECT playbook_id, lesson_id
FROM playbook_lessons
WHERE playbook_id = ?
`

func (q *Queries) ListPlaybookLessons(ctx context.Context, playbookID string) ([]PlaybookLesson, error) {
	rows, err := q.db.QueryContext(ctx, listPlaybookLessons, playbookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaybookLesson
	for rows.Next() {
		var i PlaybookLesson
		if err := rows.Scan(&i.PlaybookID, &i.LessonID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaybooksByService = `-- name: ListPlaybooksByService :many
SELECT id, trigger, statement, scope_service, scope_env, scope_team, steps_json, confidence, derived_at, last_verified, source, created_by
FROM playbooks
WHERE scope_service = ?
ORDER BY confidence DESC, derived_at DESC
`

func (q *Queries) ListPlaybooksByService(ctx context.Context, scopeService string) ([]Playbook, error) {
	rows, err := q.db.QueryContext(ctx, listPlaybooksByService, scopeService)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playbook
	for rows.Next() {
		var i Playbook
		if err := rows.Scan(
			&i.ID,
			&i.Trigger,
			&i.Statement,
			&i.ScopeService,
			&i.ScopeEnv,
			&i.ScopeTeam,
			&i.StepsJson,
			&i.Confidence,
			&i.DerivedAt,
			&i.LastVerified,
			&i.Source,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaybooksByTrigger = `-- name: ListPlaybooksByTrigger :many
SELECT id, trigger, statement, scope_service, scope_env, scope_team, steps_json, confidence, derived_at, last_verified, source, created_by
FROM playbooks
WHERE trigger = ?
ORDER BY confidence DESC, derived_at DESC
`

func (q *Queries) ListPlaybooksByTrigger(ctx context.Context, trigger string) ([]Playbook, error) {
	rows, err := q.db.QueryContext(ctx, listPlaybooksByTrigger, trigger)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playbook
	for rows.Next() {
		var i Playbook
		if err := rows.Scan(
			&i.ID,
			&i.Trigger,
			&i.Statement,
			&i.ScopeService,
			&i.ScopeEnv,
			&i.ScopeTeam,
			&i.StepsJson,
			&i.Confidence,
			&i.DerivedAt,
			&i.LastVerified,
			&i.Source,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
