// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: revoked_tokens.sql

package sqlcgen

import (
	"context"
)

const addRevokedToken = `-- name: AddRevokedToken :exec
INSERT INTO revoked_tokens (jti, revoked_at, expires_at)
VALUES (?, ?, ?)
ON CONFLICT(jti) DO NOTHING
`

type AddRevokedTokenParams struct {
	Jti       string `json:"jti"`
	RevokedAt string `json:"revoked_at"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) AddRevokedToken(ctx context.Context, arg AddRevokedTokenParams) error {
	_, err := q.db.ExecContext(ctx, addRevokedToken, arg.Jti, arg.RevokedAt, arg.ExpiresAt)
	return err
}

const isTokenRevoked = `-- name: IsTokenRevoked :one
SELECT 1 AS present
FROM revoked_tokens
WHERE jti = ?
LIMIT 1
`

func (q *Queries) IsTokenRevoked(ctx context.Context, jti string) (int64, error) {
	row := q.db.QueryRowContext(ctx, isTokenRevoked, jti)
	var present int64
	err := row.Scan(&present)
	return present, err
}

const purgeExpiredRevokedTokens = `-- name: PurgeExpiredRevokedTokens :execrows
DELETE FROM revoked_tokens WHERE expires_at < ?
`

func (q *Queries) PurgeExpiredRevokedTokens(ctx context.Context, expiresAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeExpiredRevokedTokens, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
